/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderpickup;

import java.awt.Component;
import java.awt.event.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yuvaraja
 */
public class JOrderPickup extends javax.swing.JFrame {

    private Component frame;


    
    
    public JOrderPickup() {
        initComponents();
        
         addRowToJTable();
         
         this.setLocationRelativeTo(null);
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         showDate();
         showTime();
        
    }
    
    void clearText(){
        jtxtName.setText("");
        jtxtPickupId.setText("");
        jtxtContactNo.setText("");
        jcboStatus.setSelectedItem("Picked");
    }
    
      void showDate(){
    Date d = new Date();
    SimpleDateFormat s =new SimpleDateFormat("dd-MM-yyyy");
    jlblDate.setText(s.format(d));
    }
    
    void showTime(){
     new Timer(0, new ActionListener() {
         @Override
         public void actionPerformed(ActionEvent e) {
             Date d = new Date();
             SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
             jlblTime.setText(s.format(d));
         }
     }).start();
     
       
    }
    
    
    public class Pickup {
    String name, pickupId, pickupStatus, contactNo;
 
    
    public Pickup(String custName, String pickupId, String contact, String status){
    this.name = custName;
    this.pickupId = pickupId;
    this.contactNo = contact;
    this.pickupStatus = status;
    }
}
       
    public ArrayList Pickup()
    {
        ArrayList<Pickup> list = new ArrayList<Pickup>();
        Pickup p1 = new Pickup("Max","P001","012-5874263","Not Picked");
        Pickup p2 = new Pickup("Victor","P002","012-5874263","Not Picked");
        Pickup p3 = new Pickup("James","P003","012-5874263","Not Picked");
        Pickup p4 = new Pickup("Kim","P004","012-5874263","Not Picked");
        Pickup p5 = new Pickup("Susan","P005","012-5874263","Not Picked");
        
        list.add(p1);
        list.add(p2);
        list.add(p3);
        list.add(p4);
        list.add(p5);
           
        return list;
    }
    
    public void addRowToJTable()
    {
    
        DefaultTableModel model = (DefaultTableModel) jtPickup.getModel();
        ArrayList<Pickup> list = Pickup();
        Object rowData[] = new Object[5];
        for(int i = 0; i < list.size(); i++)
        {
            rowData[0] = list.get(i).name;
            rowData[1] = list.get(i).pickupId;
            rowData[2] = list.get(i).contactNo;
            rowData[3] = list.get(i).pickupStatus;
    
  
            model.addRow(rowData);
   
    
        }
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPickup = new javax.swing.JTable();
        jtxtName = new javax.swing.JTextField();
        jtxtPickupId = new javax.swing.JTextField();
        jtxtContactNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtUpdate = new javax.swing.JButton();
        jlblDate = new javax.swing.JLabel();
        jlblTime = new javax.swing.JLabel();
        jbtClear = new javax.swing.JButton();
        jcboStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fiore Flowershop System");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Fiore Flowershop Sdn. Bhd.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Order Pickup");

        jtPickup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Pickup ID", "Contact No.", "Status", "Pickup Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPickup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPickupMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPickup);

        jLabel4.setText("Name:");

        jLabel5.setText("Pickup ID:");

        jLabel6.setText("Contact No.:");

        jLabel7.setText("Status:");

        jbtUpdate.setText("Update");
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });

        jlblDate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jlblTime.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jbtClear.setText("Clear");
        jbtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtClearActionPerformed(evt);
            }
        });

        jcboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Picked", "Not Picked", "Cancelled" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jlblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtContactNo)
                        .addComponent(jtxtPickupId)
                        .addComponent(jtxtName)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtUpdate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbtClear, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                    .addComponent(jcboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPickupId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtUpdate)
                    .addComponent(jbtClear))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jtPickupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPickupMouseClicked
  
        DefaultTableModel model = (DefaultTableModel) jtPickup.getModel();
        int selectedRowIndex = jtPickup.getSelectedRow();
        
        jtxtName.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jtxtPickupId.setText(model.getValueAt(selectedRowIndex, 1).toString());
        jtxtContactNo.setText(model.getValueAt(selectedRowIndex, 2).toString());                    
    }//GEN-LAST:event_jtPickupMouseClicked

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
    
        int i = jtPickup.getSelectedRow();
       
      if(i >= 0)
     {
        jtPickup.setValueAt(jtxtName.getText(), i, 0);
        jtPickup.setValueAt(jtxtPickupId.getText(), i, 1);
        jtPickup.setValueAt(jtxtContactNo.getText(), i, 2); 
         jtPickup.setValueAt(jlblDate.getText().toString() + " " 
                 + jlblTime.getText().toString(), i, 4);
         
        if(jcboStatus.getSelectedItem().equals("Not Picked")){ 
            jtPickup.setValueAt("Not Picked", i, 3); 
            jtPickup.setValueAt(null, i, 4);  
            
        }else if(jcboStatus.getSelectedItem().equals("Cancelled")){ 
            jtPickup.setValueAt("Cancelled", i, 3); 
            jtPickup.setValueAt(null, i, 4); 
        
        }else{
         jtPickup.setValueAt(jcboStatus.getSelectedItem().toString() ,i, 3);    
         jtPickup.setValueAt(jlblDate.getText().toString() + " " 
                 + jlblTime.getText().toString(), i, 4);
         JOptionPane.showMessageDialog(frame, "Pickup details updated.");
        } 
        
     }else{        
       JOptionPane.showMessageDialog(frame, "Update failed. Please select a customer.");
      }
      
      clearText();  
  
    }//GEN-LAST:event_jbtUpdateActionPerformed

    private void jbtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClearActionPerformed
          clearText(); 
    }//GEN-LAST:event_jbtClearActionPerformed

    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JOrderPickup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JOrderPickup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JOrderPickup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JOrderPickup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JOrderPickup().setVisible(true);
            }
        });
             
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtClear;
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JComboBox<String> jcboStatus;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JLabel jlblTime;
    private javax.swing.JTable jtPickup;
    private javax.swing.JTextField jtxtContactNo;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPickupId;
    // End of variables declaration//GEN-END:variables
}
